---
abstract: 'XS helpers for Iston'
author:
  - 'DMOL, dmol@cpan.org'
build_requires:
  ExtUtils::CBuilder: '0'
  SDL: '0'
  Test::Fatal: '0'
  Test::More: '0'
  Test::Warnings: '0'
configure_requires:
  Module::Build: '0.42'
  perl: '5.016'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Iston-XS
provides:
  Iston::XS:
    file: lib/Iston/XS.pm
    version: '0.01'
  Iston::XS::Utils:
    file: lib/Iston/XS/Utils.pm
  Iston::XS::Utils::PP:
    file: lib/Iston/XS/Utils/PP.pm
requires:
  Carp: '0'
  List::MoreUtils: '0'
  perl: '5.016'
resources:
  bugtracker: https://github.com/basiliscos/iston-xs/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/basiliscos/iston-xs
version: '0.01'
